# Generated by Django 5.2.7 on 2025-10-07 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='codigo',
            field=models.SlugField(help_text='Identificador URL-safe (min. 4).', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^[a-z0-9\\-]+$', 'Use solo minúsculas, números y guiones.')], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='espacio',
            field=models.CharField(help_text='Nombre del espacio o sala.', max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Espacio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='solicitante',
            field=models.CharField(help_text='Nombre del área o responsable.', max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Solicitante'),
        ),
    ]
