# Generated by Django 5.2.7 on 2025-12-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_aforo_and_autocode'),
        ('reservas', '0003_reserva_evento'),
    ]

    operations = [
    ]
