# Generated by Django 5.2.7 on 2025-12-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_indexes_reservas'),
        ('reservas', '0004_merge_20251216_2017'),
    ]

    operations = [
    ]
