# Generated by Django 5.2.7 on 2025-10-07 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'evento', 'verbose_name_plural': 'eventos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('convocatoria', 'En convocatoria'), ('confirmado', 'Confirmado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha',
            field=models.DateField(help_text='Formato AAAA-MM-DD. Debe ser hoy o futura.', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(help_text='Formato 24h HH:MM.', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(help_text='Nombre del espacio o dirección completa.', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(help_text='Entre 5 y 200 caracteres. Evita abreviaturas ambiguas.', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título'),
        ),
    ]
