# Generated by Django 5.2.7 on 2025-10-07 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha', '-creado'], 'verbose_name': 'reporte', 'verbose_name_plural': 'reportes'},
        ),
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(help_text='Entre 5 y 200 caracteres.', max_length=200, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Título'),
        ),
    ]
