# Generated by Django 5.2.7 on 2025-10-07 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['-creado'], 'verbose_name': 'cuenta', 'verbose_name_plural': 'cuentas'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='email',
            field=models.EmailField(help_text='Correo institucional del usuario.', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(help_text='Entre 3 y 150 caracteres.', max_length=150, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor'), ('consulta', 'Consulta')], default='consulta', max_length=20, verbose_name='Rol'),
        ),
    ]
